sudo: false

language: python

os:
  - linux

python:
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - pip install docker-compose==1.19.0
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps

install:
  - pip install -r greetings/requirements.txt
  - pip install pytest pytest-flake8

before_script:
  - flake8 --show-source .
  - py.test . -k greetings
